### ISSUE TITLE
Possible bug with DiskInfo module

### ISSUE THREAD

**Issue by PTz0uAH** [mheyer32/dopus5allamigas#2] opened 2022-05-08 17:14 UTC
Hoi fellow amiga developer, after building this majestic piece of SW and running it on my real Amiga 1230 I experienced a serious crash which seems to occur every time [DiskInfo] is selected.. A window with red & blue color bar pops up briefly (I guess showing the disk information) and the program crashes with guru meditation result  #8000 000B after reboot.. Searching for a cause led to multiple possible assumptions. 1) is it a [DiskInfo]-related thing as in a bug in the source? I guess not because no bugs are filed of ppl experiencing the same "bug", the only thing related I could find was a commit stating using mathroutines from libnix instead of proper amiga library mathlib routines.. 2) could it be because my DH0 is a 60Gb disk partitioned in 2x4Gb because of FFS limitations.. well it seems that is not logical either because [DiskInfo] also crashes when selecting RAMDISK or DF0 in my setup.. OR maybe it is something else.. anyway apart from the fact everything else is working fabulous I'm stuck on this funspoiling issue! Do I miss a library or what.. Any idea what might be going on and how to fix it perhaps, if it is a known problem? with kind regards Peter ( p.s. the environment I'm using: WSL/Ubuntu 20 with Bebbo's GCC 6.x toolchain building DOPUS for Amiga OS3.x)

**Comment by mheyer32** [comment] 2022-06-16 20:30
Hi, sorry for picking this up so late. can you please post your HW setup and what OS you're running on.
DiskInfo is the only(?) module that is using floating point calculations and the Guru 0x8000000B indicates that this is an FPU related issue.
I _think_ that DOpus is not compiling using FPU instructions (check makefile.common for  that) and instead libnix is supposed to call into the math libraries instead.
So either libnix is making FPU calls directly - which could be a bug in the compiler. Or maybe it is calling into  your machine's math libraries and these libraries erroneously emit FPU instructions when you don't have one installed.
It might also be possible you're missing math libraries, but that would probably manifest in a different way.

DOpus5 is compile with 64bit support in, so it will cope with big harddrives.

**Comment by mheyer32** [comment] 2022-06-17 06:57
I can confirm, something fishy is going on (tested by disabling FPU in WinUAE):
![image](https://user-images.githubusercontent.com/33539855/174242901-12102a61-df9c-4b45-afce-f75434a16a7f.png)

**Comment by mheyer32** [comment] 2022-06-17 17:12
I was wrong. Nothing to do with FPU. Something else is afoot.

**Comment by mheyer32** [comment] 2022-06-17 18:38
I think I found the issue. Try latest version. I have NO idea how that could have ever worked, yet I'm 100% sure I tested diskinfo before.
The issue is that while we're using libnix' math routines, the way DOpus  modules get linked prevents libnix' init code to run and thus the various math library base pointers were either NULL or pointing somewhere random...

**Comment by mheyer32** [comment] 2022-07-20 17:22
Closing. Feel free to reopen if this didn't fix it.

**Closed as completed by mheyer32** 2022-07-20 17:22 UTC

**Comment by PTz0uAH** [comment] 2022-07-23 21:49
Hi there,
I can confirm the latest commits did fix the buggy Diskinfo.module.
Testconfiguration1: RPi 4 Buster + Amiberry 5.3 running Dopus5 as Workbench replacement on OS3.2.
Building configuration used: W10/WSL/Ubuntu20.4LTS + Amiga-GCC
Thank you very much!
